# Generated by Django 5.2.11 on 2026-02-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmergencyLog',
        ),
    ]
