# Generated by Django 5.2.11 on 2026-02-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_delete_emergencylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='Temperature (°C) that triggered the event')),
                ('triggered_at', models.DateTimeField(help_text='Exact timestamp when threshold was breached')),
                ('door_was_locked', models.BooleanField(default=False, help_text='Whether the door was locked at the time of the event')),
                ('resolved', models.BooleanField(default=False, help_text='Has this event been resolved via System Reset?')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Emergency Event',
                'verbose_name_plural': 'Emergency Events',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLockdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('last_temperature', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'System Lockdown Status',
                'verbose_name_plural': 'System Lockdown Status',
            },
        ),
    ]
