# Generated by Django 5.2.11 on 2026-02-28 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_emergencyevent_systemlockdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('sensor', 'Sensor'), ('light', 'Light'), ('lock', 'Lock'), ('relay', 'Relay'), ('other', 'Other')], default='other', max_length=20)),
                ('mqtt_topic', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('degraded', 'Degraded')], default='offline', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_value', models.CharField(blank=True, default='', max_length=100)),
                ('signal_strength', models.IntegerField(default=0, help_text='Simulated signal quality 0-100%')),
                ('uptime_seconds', models.IntegerField(default=0, help_text='Cumulative uptime in seconds')),
                ('total_messages', models.IntegerField(default=0, help_text='Total MQTT messages received')),
                ('error_count', models.IntegerField(default=0, help_text='Number of errors/timeouts detected')),
                ('firmware_version', models.CharField(blank=True, default='1.0.0', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('icon', models.CharField(default='📟', max_length=10)),
                ('room', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'IoT Device',
                'verbose_name_plural': 'IoT Devices',
                'ordering': ['device_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceHealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='online', max_length=20)),
                ('signal_strength', models.IntegerField(default=0)),
                ('health_score', models.IntegerField(default=100)),
                ('value', models.CharField(blank=True, default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='dashboard.device')),
            ],
            options={
                'verbose_name': 'Device Health Log',
                'verbose_name_plural': 'Device Health Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', '-timestamp'], name='dashboard_d_device__54b705_idx')],
            },
        ),
    ]
