# Generated by Django 6.0.3 on 2026-04-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_device_devicehealthlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='ai_decision',
            field=models.CharField(blank=True, help_text='HEATER_ON, AC_ON, or STANDBY', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='outdoor_humidity',
            field=models.FloatField(blank=True, help_text='Vaddeswaram Outdoor Humidity', null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='outdoor_temp',
            field=models.FloatField(blank=True, help_text='Vaddeswaram Outdoor Temp', null=True),
        ),
    ]
