# Generated by Django 6.0.3 on 2026-04-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_sensorreading_ai_decision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Scheduler Config',
                'verbose_name_plural': 'Scheduler Config',
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='0=Monday … 6=Sunday')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('HOME', 'Home'), ('AWAY', 'Away')], default='AWAY', max_length=10)),
                ('label', models.CharField(blank=True, default='', help_text="Optional label, e.g. 'Work Hours'", max_length=60)),
            ],
            options={
                'verbose_name': 'Schedule Slot',
                'verbose_name_plural': 'Schedule Slots',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
