# Generated by Django 6.0.3 on 2026-04-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_schedulerconfig_scheduleslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='status',
            field=models.CharField(default='OK', help_text='OK, ANOMALY, or AWAY_STANDBY', max_length=20),
        ),
    ]
